import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

interface InvoiceItem {
    description: string;
    quantity: number;
    unit: string;
    price: number;
    total: number;
}

interface InvoiceData {
    shopName: string;
    shopAddress?: string;
    customerName: string;
    customerPhone?: string;
    invoiceNumber: string;
    date: string;
    items: InvoiceItem[];
    totalAmount: number;
    type: 'Invoice' | 'Quote';
}

export const generateInvoiceHTML = (data: InvoiceData) => {
    return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
            .header { text-align: center; margin-bottom: 30px; }
            .shop-name { font-size: 24px; font-weight: bold; color: #000; margin-bottom: 4px; }
            .invoice-title { font-size: 20px; font-weight: bold; text-transform: uppercase; color: #1a73e8; margin-top: 10px; }
            .meta { display: flex; justify-content: space-between; margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 20px; }
            .meta-left { text-align: left; }
            .meta-right { text-align: right; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th { text-align: left; background-color: #f8f9fa; padding: 10px; border-bottom: 2px solid #ddd; }
            td { padding: 10px; border-bottom: 1px solid #eee; }
            .total-row { font-weight: bold; font-size: 18px; }
            .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
            h3 { font-size: 14px; margin: 0; color: #666; }
            p { margin: 4px 0; font-size: 14px; }
        </style>
      </head>
      <body>
        <div class="header">
            <div class="shop-name">${data.shopName}</div>
            <p>${data.shopAddress || ''}</p>
            <div class="invoice-title">${data.type}</div>
        </div>

        <div class="meta">
            <div class="meta-left">
                <h3>Bill To:</h3>
                <p><strong>${data.customerName}</strong></p>
                <p>${data.customerPhone || ''}</p>
            </div>
            <div class="meta-right">
                <p>No: <strong>${data.invoiceNumber}</strong></p>
                <p>Date: ${data.date}</p>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th style="text-align: right;">Qty</th>
                    <th style="text-align: right;">Price</th>
                    <th style="text-align: right;">Total</th>
                </tr>
            </thead>
            <tbody>
                ${data.items.map(item => `
                    <tr>
                        <td>${item.description}</td>
                        <td style="text-align: right;">${item.quantity.toFixed(2)} ${item.unit}</td>
                        <td style="text-align: right;">${item.price.toFixed(2)}</td>
                        <td style="text-align: right;">${item.total.toFixed(2)}</td>
                    </tr>
                `).join('')}
            </tbody>
            <tfoot>
                 <tr>
                    <td colspan="3" style="text-align: right; padding-top: 20px;"><strong>Grand Total</strong></td>
                    <td style="text-align: right; padding-top: 20px;" class="total-row">${data.totalAmount.toFixed(2)}</td>
                </tr>
            </tfoot>
        </table>

        <div class="footer">
            <p>Thank you for your business!</p>
            <p>Generated by Mobile ERP</p>
        </div>
      </body>
    </html>
    `;
};

export const createAndSharePDF = async (data: InvoiceData) => {
    try {
        const html = generateInvoiceHTML(data);
        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Error generating PDF:', error);
        throw error;
    }
};
